### ISSUE TITLE
No network,Slow boot

### ISSUE THREAD

**Issue by H-sw123** [openmediavault/openmediavault-docs#107]
Hi! I installed OMV6, but I encountered a problem. When there is no network connection, the boot is very slow. How to turn off this boot detection network?

![ERROR](https://user-images.githubusercontent.com/81347510/190846793-c8a3b403-0855-409e-88cd-8bb8b1103a66.jpg)

**Comment by votdev** [comment]
Closing because this is no bug as this is a default behaviour of a Linux system. Please ask this question in the forum.
