### ISSUE TITLE
lower the hurdle for occasional doc editors by using free GitHub CodeSpace?

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#115]
**Describe the improvement you'd like**
The current workflow requires a correctly working Sphinx setup but this requirement is too much effort for occasional editors wanting to contribute just a "1 line change". Example is "broken rending" in https://github.com/openmediavault/openmediavault-docs/pull/109#issuecomment-1267353000
This is the  reason for raising this suggestion and looking for feedback.

**Additional context**
[GitHub free tire announcement of GitHub CodeSpace](https://github.blog/changelog/2022-11-09-codespace-templates)

**Comment by votdev** [comment]
CodeSpaces can be used for CI, but not the workflow you are talking about.
