### ISSUE TITLE
Reset OpenMediaVault to the default setting

### ISSUE THREAD

**Issue by GUNT0815** [openmediavault/openmediavault-docs#116]
As I reconfigured all my servers I have the need to fully reconfigure one of my omv servers. I could just reinstall OMV, but was looking for a function that just resets all paramters back to default (so no mounted devices, no user account, no smb shares, etc, just the plain installation).

Can I just delete some special files and reboot and the installation is fresh? Or do I have to go the USB-Stick way?

**Comment by votdev** [comment]
Never tried that, but maybe this will work.

```
# cp /usr/share/openmediavault/templates/config.xml /etc/openmediavault/config.xml
# omv-confdbadm populate
# omv-salt stage run prepare
# omv-salt stage run deploy
```

You can just igonre the `omv-confdbadm populate` command if you do not import current hostname, interfaces, timezone and everything else. In that case you'll loose network connectivity as well, but if you can access the system via kbd you can run `omv-firstaid` to do an initial network setup.

Note, this does not work for plugins, only the core system. Plugins need to be installed afterwards.

**Comment by GUNT0815** [comment]
Thank you for the quick reply. I will try now and report.

**Comment by GUNT0815** [comment]
I have done:

# cp /usr/share/openmediavault/templates/config.xml /etc/openmediavault/config.xml
# omv-confdbadm populate
# omv-salt stage run prepare
# omv-salt stage run deploy

Login to the gui via webpage showed only a dashboard with systemtime.

# via ssh: reboot now

# Login to webgui: stil only the systemtime 

I think I go for a fresh install.

![Screenshot 2023-02-15 140616](https://user-images.githubusercontent.com/66719836/219035532-65a13607-ac29-414e-8b78-0313db7c32ce.jpg)

**Comment by votdev** [comment]
> Login to the gui via webpage showed only a dashboard with systemtime.

I guess you did not use the `admin` user to sign in.
