### ISSUE TITLE
Home directory setup and user templates not well described

### ISSUE THREAD

**Issue by mckaygerhard** [openmediavault/openmediavault-docs#138]
The web documentation lack of important information:

- If you dont enable user home directories, and created an user.. 
    - such user will NOT have a home if you use the OVM web gui
    - such user WILL HAVE A HOME if you create it using Debian command line user tools and will be at "/home" directory​
    - "skel" templates only will be used in last case
- If you already enable user home directories, and created an user.. 
    - user directory will be created at the home chosen share resource if you create using OMV web gui
    - user directory will be created at the rootfs home directory if you use Debian user command management tools
    - "skel" templates seems to be used in both cases

Also the configuration of the home is not well described, this must be with some pictures and something like:

1. Choose a shared directory at "storage/shared-folders"
2. Setup the home directory by the creation of a new share
3. Go to "usermgmt/settings" and enable "home" setup at the checkbox
4. Later select form the box below the configured shared resource of the second step.

**Additional context**

https://forum.openmediavault.org/index.php?thread/41310-where-is-bashrc-file/&postID=294339#post294339

**Comment by votdev** [comment]
Since you have certainly found the solution to the problem through your own experience, it would be really nice if you would contribute the changes to the documentation.

**Comment by ph818** [comment]
I've made a pull request as a starting point here: https://github.com/openmediavault/openmediavault-docs/compare/master...ph818:patch-2?expand=1

double-check that it is accurate and I am not misunderstanding the situation as of in OMV 7

**Comment by mckaygerhard** [comment]
> I've made a pull request as a starting point here: https://github.com/openmediavault/openmediavault-docs/compare/master...ph818:patch-2?expand=1

That is pretty weak and minimalist.. please can you take a note at https://github.com/mckaygerhard/openmediavault-docs/blob/master-users-improve/administration/users.rst 

Documentation must be improve it **a huge**! @ph818

**Comment by ph818** [comment]
I'm glad you did more work -- I prefer to start small :)

**Comment by mckaygerhard** [comment]
yeah @ph818 but was cos i work so so much with OMV on this month.. i really hate the onedrive service and i am trying to promote the NAS OMV usage in my people and some friends.. promote more free software and not the usage of Windos shit servers for sharing purposes..

**Comment by mckaygerhard** [comment]
yeah @ph818 but was cos i work so so much with OMV on this month.. i really hate the onedrive service and i am trying to promote the NAS OMV usage in my people and some friends.. promote more free software and not the usage of Windos shit servers for sharing purposes..

in this case minimalist is a fail, and not the way.. documentation is the key to users and must provide all essential information.. 

of course we will not describe all the things  i removed some obvious parts and add very important missing ones.. this work that i did its necessary and clarifies many void parts
