### ISSUE TITLE
doc improvement: management of RAID setups

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#72]
**Is your feature request related to a problem? Please describe.**
Today only very basic information is documented, the pointer to advanced topics is badly noticeable ([see forum post](https://forum.openmediavault.org/index.php?thread/37628-omv-neue-festplatte/&postID=263164#post263164))

**Describe the solution you'd like**
Make it obvious for readers where advanced topics are explained

related to openmediavault/openmediavault#887

**Comment by mi-hol** [comment]
The goal is to find a better approach to document "management of RAID configuration" for an OMV server.

This issue's intent is to discuss solution ideas **before** changing the existing documentation!

Reference:
[RAID.rst](https://github.com/openmediavault/openmediavault-docs/blob/master/administration/storage/raid.rst)

Initial source of text in RAID.rst seems to be [linux wiki](https://raid.wiki.kernel.org/index.php/A_guide_to_mdadm#Modes)

Perceived issues with the current doc are:

- RAID is a very complex topic with 2 "flavours" software and hardware RAID
- RAID is requiring deep technical IT knowledge to master it
- only software RAID is currently mentioned in doc
- the majority of OMV admins don't have the deep technical IT knowledge
- also non-IT admins seem to confuse RAID with backup, hence have wrong expectations upon the benefits of RAID
- the technical hurdle of initial RAID configuration is overcome by following tutorials that make it appear as "a simple task"
- issue surface when after some time a HDD becomes defectiv or a capacity change is needed
-

**Comment by mi-hol** [comment]
Solution idea:

- Add a strong warning about required IT skills
- correctly position availability versus backup requirements
- repeat "RAID is not a backup
- link to the "backup" topic in "new user content"
- remove the current (copied) text
- add a table-of-content (TOC) with references to the wiki
-  advanced usage https://raid.wiki.kernel.org/index.php/A_guide_to_mdadm

describing the necessary details like:

4.4 "Grow"ing non-parity raid arrays
4.4.1 Raid 0
4.4.2 Raid 1
4.4.3 Raid 1+0
4.4.4 Raid 10
4.5 "Grow"ing parity raid arrays
4.5.1 Raid 4
4.5.2 Raid 5
4.5.3 Raid 6

**Comment by mi-hol** [comment]
Info from Volker: OMV UI disallows creation of software RAID already since a long time (version?) when a disc connected via USB is detected. 
**Note this fact is not mentioned in manual currently!**
I'd suggest to display a Warning in UI if a software RAID was created via command line!

**Comment by votdev** [comment]
> Note this fact is not mentioned in manual currently!

But the UI is mentioning that. I feat that most of the users do not use the documentation.

![Bildschirmfoto vom 2021-02-07 13-07-44](https://user-images.githubusercontent.com/1897962/107145979-86ca5900-6945-11eb-82a0-3386dbe0f120.png)

> I'd suggest to display a Warning in UI if a software RAID was created via command line!

That's not possible. OMV is stateless here, this means it does not store any information in the database when the RAID is created. Because of that it is impossible to check whether a RAID was created via UI or CLI.
