### ISSUE TITLE
changes made in openmediavault-docs/plugins.rst don't appear on ReadTheDocs

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#80]
@votdev  Change from 6Apr2021 doesn't appear on official doc despite being merged

**Comment by votdev** [comment]
They are rendered correctly for the master branch, see https://openmediavault.readthedocs.io/en/latest/plugins.html. If you want to see them in the 5.x branch, then the correspondig PR must be backported to this branch.

**Comment by mi-hol** [comment]
https://blog.boombatower.com/2012/06/22/automatically-backport-commits-using-git suggests this to be a task for an experienced git admin, which I'm certainly not :(
Could you please step in?

**Comment by votdev** [comment]
Done. You can simply do that yourself the next time with the following lines.
You can find the commit id in the commit [history](https://github.com/openmediavault/openmediavault-docs/commits/master/plugins.rst) by clicking on the `Copy to clipboard` button. 
```
 ~/git/openmediavault-docs   5.x ✔  $ git checkout -b backport_issue_69
Zu neuem Branch 'backport_issue_69' gewechselt
 ~/git/openmediavault-docs   backport_issue_69 ✔  $ git cherry-pick -x --signoff --no-commit 21397da77888f0da54c8bd141ca11c0e68e6cb2b
```
Now commit the changes and push the branch. Finally create a PR out of that branch.

**Comment by mi-hol** [comment]
Thank you so much for performing & documenting the required steps. Will try it next time
