### ISSUE TITLE
add more details about official plugins in doc

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#81]
- add "USB backup plugin uses rsync to perform the backup. Because of that everything should be visible when selecting 'Rsync - Jobs' in the log page." as mentioned in https://github.com/openmediavault/openmediavault/issues/686

- add links from openmediavault-docs/plugins.rst

**Comment by mi-hol** [comment]
@votdev with the recent addition of podman-based containers it seems that preferences for extending OMV have changed.
is the current text in https://openmediavault.readthedocs.io/en/stable/plugins.html#plugins still correct?

**Comment by votdev** [comment]
> @votdev with the recent addition of podman-based containers it seems that preferences for extending OMV have changed. is the current text in [openmediavault.readthedocs.io/en/stable/plugins.html#plugins](https://openmediavault.readthedocs.io/en/stable/plugins.html#plugins) still correct?

What do you exactly mean?

**Comment by ryecoaaron** [comment]
Why not make it docker and podman instead of just one or the other?

**Comment by votdev** [comment]
The plugins list has been fixed with https://github.com/openmediavault/openmediavault-docs/commit/dc8da49c4a38c52b70b56850f20cad9737a1281d.

**Comment by votdev** [comment]
> 1. in section "Plugins" the text part:
>        "It is still possible to install regular software" this seems no longer desired, instead
>        "containerized software like Docker." but instead of docker, podman seems the new preference.

There is no preference. The only reason why Podman is used for the plugins is that it does not need a daemon and IMO Podman is the successor of Docker.

Can you make a suggestion how to phrase the sentence you want to change?

**Comment by mi-hol** [comment]
My suggestion:

replace "It is still possible to install regular software or containerized software like Docker."
with "While it is still possible to install regular software alongside openmediavault, installing **containerized** software build with podman or Docker is highly recommended. This recommendation stems from many issues caused by later version updates that made openmediavault or other software unusable due to introducing conflicting component dependencies."

Any comments?

**Comment by mi-hol** [comment]
@votdev No comments, so shall I create a PR with this changed wording?

**Comment by votdev** [comment]
> My suggestion:
> 
> replace "It is still possible to install regular software or containerized software like Docker." with "While it is still possible to install regular software alongside openmediavault, installing instead **containerized** software build with podman or Docker is highly recommended. This recommendation stems from many issues caused by later version updates that made openmediavault or other software unusable due to introducing conflicting component dependencies."
> 
> Any comments?

This sounds good. Can you open a PR for that?
