### ISSUE TITLE
correct "mkconf" references in OMV 5.x docs 

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#83]
mkconf seems not used since version 5
reference https://forum.openmediavault.org/index.php?thread/39537-omv-tool-documentation/&postID=277666#post277666

**Comment by votdev** [comment]
Could you please go a little bit more into detail what needs to be done? Such issues are pretty useless. I do not have the time to read through a complete forum post to get the information. All information should be mentioned here.

**Comment by mi-hol** [comment]
text was just a reminder to myself to avoid forgetting but forgot to assign it to myself :)

open actions:
- verify ryecoaaron's and gderf's statements in the specifically referenced post are correct 

> omv-mkconf is only relevant for pre-5.x versions of OMV.
> All the mkconf scripts have been removed from my OMV 5 

- if confirmed, remove mkconf from docs and repository (as title states)

**Comment by mi-hol** [comment]
openmediavault/deb/openmediavault/debian/changelog
includes the statement:
"openmediavault (5.0-1) unstable; urgency=low
  * The omv-salt CLI command superseds omv-mkconf."

but below listed official plugins still use it for "Action to be done depending on the previous version."

- deb/openmediavault-shairport/debian/openmediavault-shairport.postinst
- deb/openmediavault-usbbackup/debian/openmediavault-usbbackup.postinst
- deb/openmediavault-nut/debian/openmediavault-nut.postinst

**Comment by mi-hol** [comment]
@votdev would it make sense to remove omv-mkconf from the 3 plugins listed above?

**Comment by ryecoaaron** [comment]
@mi-hol You really need to look at the code and listen to people who know.

It doesn't matter if it is in the code because the omv-mkconf binary does not exist in 5.x.  Look in this directory - https://github.com/openmediavault/openmediavault/tree/5.x/deb/openmediavault/usr/sbin

It doesn't matter if it is in the postinst script because it is only called in legacy.  In the shairport plugin, it would only be called if the version was less than 2.4.  In the usbbackup plugin, only if less than 4.0.7.  In the nut plugin, only if less than 3.0.2.  If Volker chooses to leave that code in there (knowing it would never be called) for historical reasons, that is his right.

**Comment by mi-hol** [comment]
@ryecoaaron I am listening, that's the reason I tried to verify the statements made.
If they are confirm a cleanup of docs is required.
Obviously I'm still learning and your reply adds another (previously unknown) piece of the puzzle

**Comment by ryecoaaron** [comment]
Volker shouldn't have to "verify" everything.  I think I should classify as an expert and not need every statement I make verified.  That is a waste of Volker's time.

**Comment by mi-hol** [comment]
@votdev your commit https://github.com/openmediavault/openmediavault-docs/commit/92eade8a619c7c715699cf81343cd91eb93d1e91 removed some references to obsolete mkconf utility but 4 references are still found. 

Its not clear to me how I could correct them. Could you please step in?
To see them https://openmediavault.readthedocs.io/en/5.x/search.html?q=mkconf&check_keywords=yes&area=default

**Comment by mi-hol** [comment]
> Volker shouldn't have to "verify" everything. I think I should classify as an expert and not need every statement I make verified. That is a waste of Volker's time.

I'm not a native speaker, hence "verify" may be the wrong word. The goal is to make the documentation consistent end correct.
You are welcome to make a contribution based on your knowledge.
