### ISSUE TITLE
doc build process does not expand |omv| |webui|  used in headlines

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#86]
![image](https://user-images.githubusercontent.com/22799428/124891435-45fc6c00-dfd9-11eb-9350-2f8b13853b86.png)

**Comment by votdev** [comment]
Oh, yes, i remember that Sphinx does not support that because of whatever reason.

**Comment by mi-hol** [comment]
Shall I check Sphinx docs & issues?

**Comment by votdev** [comment]
> Shall I check Sphinx docs & issues?

No necessary, it simply does not work. The workaround to use CSS is a no go. We need to replace these substitutions wit their origin values.

References:
- https://github.com/sphinx-doc/sphinx/issues/3151
- https://sourceforge.net/p/docutils/feature-requests/53/
