### ISSUE TITLE
add troubleshooting for errors as result of "Apply configuration change"

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#88]
lift knowhow from examples in forum into doc section "Troubleshooting"
 https://forum.openmediavault.org/index.php?thread/37269-upgrade-scripts-for-non-interactive-major-release-upgrades-2-3-3-4-4-5/&postID=279556#post279556

**Comment by votdev** [comment]
Please summarize what to add. Please don't expect that someone reads 11 pages of posts in the forum to get this information. Maybe the better solution is to create a PR that contains what you think that needs to be added to the documentation to fix this issue.
