### ISSUE TITLE
"New User Guide" in V5 is not available in "latest" version

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#98]
**Describe the improvement you'd like**
Please add it to "latest"

**Additional context**
V5:
![image](https://user-images.githubusercontent.com/22799428/148603210-ee3fb99f-8e14-46d6-9632-45ce74f0422c.png)

latest:
![image](https://user-images.githubusercontent.com/22799428/148603320-bb61e7e2-cd58-4e8d-b087-ed2a9fb002b6.png)

**Comment by flmaxey** [comment]
It's written -> OMV6 [https://wiki.omv-extras.org/doku.php?id=omv6_new_user_guide](url)
I'm waiting for the "Latest" to become the 6.X branch.  At that point, I'll but up a graphic and redirect to the new Guide.

I'm breaking the 5.X document into two separate documents.  A user guide and a maintenance document.

**Comment by mi-hol** [comment]
Thanks, great news. Appreciate the effort invested

**Comment by mi-hol** [comment]
issue solved
